<a href="https://colab.research.google.com/github/Shameem-Yuseph/DSA_2025/blob/main/Numpy_and_pandas_SHAMEEM_YUSEPH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PANDAS ACTIVITY

In [ ]:
import pandas as pd
import numpy as np

# 1. Load dataset (use seaborn’s Titanic dataset if CSV not available)
import seaborn as sns
titanic = sns.load_dataset("titanic")

# Display first 10 rows
print("\n1. First 10 rows:")
print(titanic.head(10))

# 2. Missing values count
print("\n2. Missing values in each column:")
print(titanic.isnull().sum())

# 3. Percentage survived grouped by gender
print("\n3. Percentage of passengers who survived, grouped by gender:")
survival_gender = titanic.groupby("sex")["survived"].mean() * 100
print(survival_gender)

# 4. Age stats
print("\n4. Age statistics:")
print("Average age:", titanic["age"].mean())
print("Median age:", titanic["age"].median())
print("Std deviation of age:", titanic["age"].std())

# 5. Passenger count by class
print("\n5. Passengers in each class:")
print(titanic["pclass"].value_counts())

# 6. Female, under 18, survived
print("\n6. Female passengers under 18 who survived:")
print(titanic[(titanic["sex"] == "female") & (titanic["age"] < 18) & (titanic["survived"] == 1)])

# 7. Replace missing ages with median
median_age = titanic["age"].median()
titanic["age"].fillna(median_age, inplace=True)
print("\n7. Missing ages replaced with median.")

# 8. Create age_group column
def age_group(age):
    if age < 18:
        return "Child"
    elif age <= 60:
        return "Adult"
    else:
        return "Senior"

titanic["age_group"] = titanic["age"].apply(age_group)
print("\n8. Age groups created:")
print(titanic[["age", "age_group"]].head(10))

# 9. Top 5 by highest fare
print("\n9. Top 5 passengers by highest fare:")
print(titanic.sort_values("fare", ascending=False).head(5))

# 10. Average fare grouped by class & gender
print("\n10. Average fare grouped by pclass and sex:")
print(titanic.groupby(["pclass", "sex"])["fare"].mean())

# 11. Rename columns
titanic.rename(columns={"sex": "gender", "fare": "ticket_fare"}, inplace=True)
print("\n11. Columns renamed. New column names:")
print(titanic.columns)

# 12. Survival count by class
print("\n12. Survival count grouped by class:")
print(titanic.groupby("pclass")["survived"].value_counts())

# 13. Average age grouped by class and gender
print("\n13. Average age by class and gender:")
print(titanic.groupby(["pclass", "gender"])["age"].mean())


1. First 10 rows:
   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C

/tmp/ipython-input-2559321163.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["age"].fillna(median_age, inplace=True)


NUMPY ASSESSMENT

In [ ]:
import numpy as np

# ----------------------------------------------------------------
# 1. Array from 10 to 49, reshape into 4x10, extract last column
arr = np.arange(10, 50)       # values from 10 to 49
matrix = arr.reshape(4, 10)   # reshape 4x10
last_col = matrix[:, -1]      # extract last column
print("1. Reshaped 4x10 matrix:\n", matrix)
print("Last column:\n", last_col)

# ----------------------------------------------------------------
# 2. Two 3x3 matrices (all 5s and 1–9)
A = np.full((3, 3), 5)                # all 5s
B = np.arange(1, 10).reshape(3, 3)    # values 1–9
add = A + B
multiply = A * B
transpose = multiply.T
print("\n2. Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B:\n", add)
print("A * B (element-wise):\n", multiply)
print("Transpose of result:\n", transpose)

# ----------------------------------------------------------------
# 3. Random 15 integers, replace >50 with -1, count replaced
rand_arr = np.random.randint(10, 101, size=15)
replaced = np.where(rand_arr > 50, -1, rand_arr)
count_replaced = np.sum(rand_arr > 50)
print("\n3. Original array:\n", rand_arr)
print("After replacement:\n", replaced)
print("Count replaced:", count_replaced)

# ----------------------------------------------------------------
# 4. 5x4 random array (0–1), row with max sum, normalize rows
arr = np.random.rand(5, 4)    # random values 0–1
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)
normalized = arr / arr.sum(axis=1, keepdims=True)
print("\n4. Random 5x4 array:\n", arr)
print("Row sums:", row_sums)
print("Row with max sum (index):", max_row_index)
print("Normalized array:\n", normalized)

# ----------------------------------------------------------------
# 5. Find unique elements and duplicates
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_vals = np.unique(arr)
duplicates = np.array([x for x in unique_vals if np.sum(arr == x) > 1])
print("\n5. Unique elements:", unique_vals)
print("Duplicates:", duplicates)

# ----------------------------------------------------------------
# 6. 6x6 array with 1–36, extract middle 4x4, then even numbers
matrix = np.arange(1, 37).reshape(6, 6)
submatrix = matrix[1:5, 1:5]          # middle 4x4
even_numbers = submatrix[submatrix % 2 == 0]
print("\n6. 6x6 matrix:\n", matrix)
print("Middle 4x4 submatrix:\n", submatrix)
print("Even numbers from submatrix:", even_numbers)

import numpy as np

# ----------------------------------------------------------------
# 7. Generate (3,4), reshape to (2,6), flatten, reshape (4,3)
arr = np.arange(12).reshape(3, 4)
reshaped = arr.reshape(2, 6)
flattened = reshaped.flatten()
back_to_4x3 = flattened.reshape(4, 3)
print("7. Original (3x4):\n", arr)
print("Reshaped (2x6):\n", reshaped)
print("Flattened 1D:", flattened)
print("Back to (4x3):\n", back_to_4x3)

# ----------------------------------------------------------------
# 8. Append new row and new column
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])             # append new row
a = np.column_stack([a, [7, 8, 9]])    # append new column
print("\n8. After appending row & column:\n", a)

# ----------------------------------------------------------------
# 9. Join arrays, reshape 3x3, extract diagonal
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joined = np.concatenate([a, b, c])
matrix = joined.reshape(3, 3)
diagonal = np.diag(matrix)
print("\n9. Joined array:", joined)
print("Reshaped 3x3 matrix:\n", matrix)
print("Diagonal elements:", diagonal)

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# 10. Numbers 1–20 divisible by 3 or 5
arr = np.arange(1, 21)
divisible = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = divisible.size
print("\n10. Numbers divisible by 3 or 5:", divisible)
print("Count:", count)

1. Reshaped 4x10 matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last column:
 [19 29 39 49]

2. Matrix A:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A + B:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
A * B (element-wise):
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose of result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]

3. Original array:
 [ 91 100  95  27  16  10  93  74  54  10  64  25  65  87  28]
After replacement:
 [-1 -1 -1 27 16 10 -1 -1 -1 10 -1 25 -1 -1 28]
Count replaced: 9

4. Random 5x4 array:
 [[0.30026908 0.05634696 0.34270708 0.7697582 ]
 [0.0826219  0.96906992 0.07213825 0.15382813]
 [0.9663478  0.20755594 0.23298175 0.71176271]
 [0.26364476 0.79231435 0.06411266 0.84641156]
 [0.91657796 0.29394342 0.39557107 0.19027389]]
Row sums: [1.46908132 1.27765821 2.11864821 1.96648333 1.79636634]
Row with max sum (index): 2
Normalized array:
 [[0.20439241 0.03835523 0.